import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://xcdboqdwkycagrzzrfrk.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjZGJvcWR3a3ljYWdyenpyZnJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5Njg0MTYsImV4cCI6MjA1MzU0NDQxNn0.ARZH1dit0FA8msrtOY4vDDPe5SIJvtRVgvV4k50VmMI')